### ISSUE TITLE
Propagate fields of inner elements

### ISSUE THREAD

**Issue by KizzyCode** [Hoverbear/getset#26]
Often you've structs like
```Rust
struct MyStruct {
    field_a: TypeA,
    field_b: TypeB
}
struct MyAdvancedStruct {
    inner: MyStruct,
    advanced_a: AdvTypeA,
    advanced_b: AdvTypeB
}
```
(or even simpler a new-type wrapper like `struct MyAdvancedStruct(MyStruct)`).

It would be cool if we could easily propagate the fields from the inner structs to the outer struct; e.g. like this:
```Rust
struct MyAdvancedStruct {
    #[get_inner_pub = "field_a"] inner: MyStruct,
    #[get = "pub"] advanced_a: AdvTypeA,
    #[get = "pub"] advanced_b: AdvTypeB
}
```
which would create the getters `field_a`, `advanced_a` and `advanced_b` for `MyAdvancedStruct`.

AFAIK this shouldn't be too hard and I'd be willing to implement this if this is considered to be in the scope of this crate 😊

**Comment by Boscop** [comment]
I don't think it's in the scope of this crate. Especially considering that this crate works very well with the `delegate` crate, which is orthogonal to this. 
You can do what you want already by combining both crates :)
Btw, for different but related use cases there's also the shrinkwrap crate.

**Comment by KizzyCode** [comment]
Ah, cool; I didn't know those crates – ty 😊

**Comment by benediktsatalia** [comment]
> I don't think it's in the scope of this crate. Especially considering that this crate works very well with the `delegate` crate, which is orthogonal to this. You can do what you want already by combining both crates :) Btw, for different but related use cases there's also the shrinkwrap crate.

I still think there could be a cool feature to combine those two crates. Yes we can use `delegate` but then we have to type out all the getter signatures which is kind of almost the same boilerplate than just writing the getters ourselves since the signature is most of the work. And if you add fields later on or change getter/setter configurations later on you need to also add / change the signatures.

So I think it would be really cool if there is some builtin functionality that can provide the getter/setter function signatures of the inner type to the delegate macro.
