### ISSUE TITLE
Writing multiple attributes in one line? 

### ISSUE THREAD

**Issue by Boscop** [Hoverbear/getset#5]
It would be nice to be able to write multiple getset attributes in one line, to reduce verbosity, but when I do (e.g. `#[get = "pub", set = "pub"]`) the proc-macro panics..

Can you make it work, please? :)

**Comment by Hoverbear** [comment]
Yes I'd like this. :)

**Comment by Boscop** [comment]
I think it would be desirable to allow listing all getters/setters for a field in one line :)

**Comment by Hoverbear** [comment]
Yeah, I totally agree. Just need to think of the best way to do it! :thinking:

**Comment by CreepySkeleton** [comment]
### Current proposal is a no go

According to https://github.com/rust-lang/rust/issues/55208, this is simple impossible since, even though attribute's syntax was relaxed a bit (a lot), it still requires attributes to correspond to this grammar:
```
PATH
PATH `(` TOKEN_STREAM `)`
PATH `[` TOKEN_STREAM `]`
PATH `{` TOKEN_STREAM `}`
PATH = TOKEN_TREE
```

In other words, the first path must be followed (optionally) by one of `{`, `(`, `[`, `=`.

### Alternative proposal

Support both forms:

```rust
// old form
#[get]
#[set]
#[whatever]

// new form
#[getset(get, set, whatever)]
```

It's pretty easy to disambiguate them, no breaking change is needed. Not to mention that almost every other derive macro out there uses `#[name(parameters)]` form. 

I would be willing to send such a PR.

**Comment by Hoverbear** [comment]
@CreepySkeleton It sounds good to me. :)  Please feel encouraged to open a PR, let me know if I can help with anything!

**Comment by CreepySkeleton** [comment]
@Hoverbear could you please review #47 and #48 so I can stack the upcoming work on top of them?

**Comment by Hoverbear** [comment]
Yes just give me a day or so, travelling from China. :)

**Comment by Hoverbear** [comment]
@CreepySkeleton Those looked great. :) Thanks so much for the stuff so far! Sorry about the delays.
